# -*- coding: utf-8 -*-
"""chat_bot_superstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAL-QNl7nDUfr1cgl17U3nTeSMSUrPdn

.

# ChatBot con Superstore:
-----------------------------------------------------
"""

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
from datetime import datetime
import os

# ------------------------------
# Archivo Excel
# ------------------------------
EXCEL_FILE = "/content/superstore.xlsx"

def save_interaction(user_msg, bot_response):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    df_new = pd.DataFrame({
        "timestamp": [timestamp],
        "usuario": [user_msg],
        "bot": [bot_response]
    })
    if os.path.exists(EXCEL_FILE):
        df_existing = pd.read_excel(EXCEL_FILE)
        df_final = pd.concat([df_existing, df_new], ignore_index=True)
    else:
        df_final = df_new
    df_final.to_excel(EXCEL_FILE, index=False)

# ------------------------------
# Base FAQ
# ------------------------------ # https://longdogechallenge.com/                         https://thatsthefinger.com/  https://cat-bounce.com/
faq_data = {
    # Bloque ventas/ganancias
    "ventas": "📊 Las ventas totales alcanzaron **$228.8M** en Texas y **$225.8M** en California como los estados líderes.",
    "top_sales": "🏆 El estado con mayores ventas fue **Texas con $228.8M**, seguido de **California con $225.8M**.",
    "resumen_ventas": "📝 En general, algunos estados muestran fuertes ingresos en ventas, pero varios como Texas y Pennsylvania reportan pérdidas en ganancias.",

    # Bloque entregas/tiempos
    "entregas": "📦 El tiempo promedio de entrega es de **9.8 días para Office Supplies**, **8.9 días para Furniture** y **8.5 días para Technology**.",
    "mejoras": "🚀 Se recomienda optimizar los tiempos de entrega en *Office Supplies*, ya que son los más largos.",
    "comparacion": "📊 Office Supplies tiene el mayor tiempo de entrega (**+1 día** sobre Furniture y Technology).",
    "resumen_entregas": "📝 En general, los tiempos son similares entre categorías, pero hay oportunidad de mejora clara en Office Supplies.",
    # Productos comportamiento
    "productos_top": "🏆 Los estados con mejores resultados son California y New York, donde los productos más vendidos también son rentables.",
    "productos_problema": "⚠️ En Texas, las ventas son altas pero con pérdidas millonarias. Recomendación: ajustar precios o analizar productos poco rentables.",
    "estrategia_descuentos": "💡 Aplicar descuentos mayores en productos de baja rotación y limitarlos en productos de alta demanda para mejorar la rentabilidad.",
    # Saludo general
    "saludo": "🛒  ¡Hola! Soy tu asistente Laura de Superstore. Pregúntame sobre ventas, productos, descuentos, tiempos de entrega o recomendaciones de mejora."


}

training_phrases = {
    # Ventas/Ganancias
    "ventas": ["dime las ventas", "cómo van las ventas", "ventas por estado", "informe de ventas", "total de ventas acumuladas", "ventas más altas", "ventas de california", "ventas de texas"],
    "ganancias": ["cómo van las ganancias", "ganancias por estado", "informe de ganancias", "estados con pérdidas", "ganancias acumuladas", "cuáles fueron las mayores ganancias"],
    "top_sales": ["quién tuvo más ventas", "top ventas", "estado con más ventas", "ranking de ventas", "ventas más altas en estados"],
    "resumen_ventas": ["dame un resumen de ventas", "resumen general de ganancias", "balance de ventas y ganancias", "cómo estuvo el rendimiento", "resumen de ventas"],

    # Entregas/Mejoras
    "entregas": ["tiempos de entrega", "promedio de entregas", "cuánto tardan los envíos", "tiempo de entrega por categoría", "duración promedio de entregas"],
    "mejoras": ["dónde podemos mejorar", "recomendaciones de mejora", "qué categoría tarda más", "oportunidades de mejora", "mejorar tiempos de entrega"],
    "comparacion": ["comparar tiempos de entrega", "qué categoría es más rápida", "cuál tarda más en entregarse", "diferencias de entrega entre categorías"],
    "resumen_entregas": ["resumen de entregas", "balance de tiempos", "estado actual de los envíos", "reporte de entregas", "resumen general de entregas"],
    #
    "mejoras_logistica": ["mejoras logísticas", "cómo reducir tiempos de entrega", "qué categoría entrega más lento", "optimizar entregas"],
    "mejoras_financieras": ["mejoras financieras", "estados con pérdidas", "dónde ajustar márgenes", "rendimiento negativo"],
    "productos_top": ["productos más rentables", "productos estrella", "qué productos funcionan mejor", "top productos"],
    "productos_problema": ["productos con pérdidas", "productos poco rentables", "qué productos revisar", "problemas con productos"],
    "estrategia_descuentos": ["descuentos", "qué estrategia de descuentos seguir", "descuentos recomendados", "cómo aplicar promociones"],

    # Saludo
    "saludo": ["hola", "buenas", "qué tal", "hey", "saludos"],
}


# ------------------------------
# Entrenamiento NLP
# ------------------------------
X, y = [], []
for intent, phrases in training_phrases.items():
    for phrase in phrases:
        X.append(phrase)
        y.append(intent)

vectorizer = TfidfVectorizer()
X_vec = vectorizer.fit_transform(X)
model = NearestNeighbors(n_neighbors=1, metric="cosine").fit(X_vec)

def predict_intent(user_input):
    user_vec = vectorizer.transform([user_input])
    dist, idx = model.kneighbors(user_vec)
    intent = y[idx[0][0]]
    confidence = 1 - dist[0][0]
    return intent if confidence >= 0.5 else None

# ------------------------------
# Lógica del Chatbot
# ------------------------------
def chatbot(user_input, history):
    intent = predict_intent(user_input)
    if intent:
        response = faq_data[intent]
    else:
        response = "❓ No entendí tu pregunta. Pregunta por los siguientes temas **ventas, productos, descuentos o recomendaciones de mejora**."

    save_interaction(user_input, response)

    # Si es reporte, añadimos link a gráfico
    if intent == "reporte":
        df = pd.DataFrame({
            "Mes": ["Enero", "Febrero", "Marzo", "Abril"],
            "Ventas": [10000, 12000, 12500, 13500]
        })
        fig, ax = plt.subplots()
        ax.plot(df["Mes"], df["Ventas"], marker="o")
        ax.set_title("Tendencia de Ventas")
        ax.set_ylabel("USD")
        plt.savefig("reporte.png")
        plt.close(fig)
        response += "\n\n![Reporte](file=reporte.png)"

    history.append({"role": "assistant", "content": response})
    return history

# ------------------------------
# Interfaz Gradio
# ------------------------------
with gr.Blocks() as demo:
    gr.Markdown("## 🛒  ChatBot de Superstore")
    chatbot_ui = gr.ChatInterface(
        fn=chatbot,
        type="messages",
        title=" 🛒 ChatBot Superstore",
        description="🛒  ¡Hola! Soy tu asistente Laura de Superstore. Pregúntame sobre ventas, productos, descuentos, tiempos de entrega o recomendaciones de mejora."
    )

demo.launch(share=True, debug=True)